name: 'Catalina tester'
description: 'Creates tmp DB, run migration files against DB and then drop it'
inputs:
  db-image:
    description: 'Database docker image'
    required: true
    default: 'mysql'
  db-tag:
    description: 'Database docker image tag'
    required: true
    default: 'alpine'
  db-url:
    description: 'Database url'
    required: true
    default: 'localhost'
  db-user:
    description: 'Database user'
    required: true
    default: 'admin'
  db-password:
    description: 'Database password'
    required: true
    default: '123456'
  db-port:
    description: 'Database port'
    required: true
    default: '3306'
runs:
  using: 'composite'
  steps:
    - name: 'Set Github Path'
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: 'Run slim DB container'
      run: run_slim_db.sh
      shell: 'bash'

    - name: 'Clean up'
      run: clean_up.sh
      shell: 'bash'