name: 'Slim DB'
description: 'Creates a new empty database that is ephemeral'
inputs:
  engine:
    description: 'Database engine'
    required: true
    default: 'mysql'
  db-url:
    description: 'Database engine'
    required: true
    default: 'localhost'
  db-user:
    description: 'Database user'
    required: true
    default: 'admin'
  db-password:
    description: 'Database password'
    required: true
    default: '123456'
  db-port:
    description: 'Database port'
    required: true
    default: '3306'
runs:
  using: 'composite'
  steps:
    - name: 'Set Github Path'
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: 'POC running arbitrary container'
      run: run_container.sh
      shell: 'bash'