name: 'Migration tester'
description: 'Tests migration files agains a provisioned slim database instance'
inputs:
  db-url:
    description: 'Database engine'
    required: true
    default: 'localhost'
  db-user:
    description: 'Database user'
    required: true
    default: 'admin'
  db-password:
    description: 'Database password'
    required: true
    default: '123456'
  db-port:
    description: 'Database port'
    required: true
    default: '3306'