on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: test_migrations
      name: Test db migrations
      uses: ./
      with:
        db-image-name: 'mcr.microsoft.com/mssql/server'
        db-image-tag: '2019-latest'
        rdbms: 'mssql'
