on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: test_migrations
      name: Test db migrations
      uses: ./
      with:
        db-host-port: 1433
        db-image-name: 'mcr.microsoft.com/mssql/server'
        db-image-tag: '2019-latest'
        db-internal-port: 1433
        db-password: 'yourStrong(!)Password'
        db-user: 'sa'
        knex-image-name: 'knex'
        knex-image-tag: 'latest'
        rdbms: 'mssql'
